import {
  StyleSheet,
  Platform,
  Dimensions,
  NativeModules,
  StatusBar,
} from 'react-native'

const { width: windowWidth, height: windowHeight } = Dimensions.get('window')

export default StyleSheet.create({
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
  underline: { textDecorationLine: 'underline' },
  statusBarBackground: {
    height: StatusBar.currentHeight,
    ...Platform.select({
      ios: {
        backgroundColor: '#333',
      },
      android: {
        backgroundColor: '#aaa',
      },
    }),
  },
  changedContainer: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  topContainer: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  logoContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 20,
  },
  logo: {
    width: windowWidth * 0.08,
    aspectRatio: 1 / 2,
    alignSelf: 'center',
    marginTop: windowWidth * 0.01,
  },
  title: {
    color: '#FF473C',
    fontFamily: 'RobotoMono',
    alignSelf: 'center',
    fontSize: windowWidth * 0.1,
    marginHorizontal: windowWidth * 0.03,
  },
  subtitle: {
    color: '#ccc',
    padding: 10,
    fontFamily: 'RobotoMono',
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: windowWidth * 0.03,
    marginBottom: 10,
    width: windowWidth * 0.7,
  },
  buttonContainer: {
    alignContent: 'center',
    padding: 20,
  },
  mainButton: {
    fontWeight: '600',
    paddingTop: 5,
    padding: 8,
    margin: 10,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#000',
    borderRadius: 25,
    borderWidth: 3,
    borderColor: '#000',
  },
  button: {
    paddingTop: 0,
    padding: 3,
    alignSelf: 'center',
    borderRadius: 20,
    borderWidth: 3,
  },
  buttonText: {
    fontFamily: 'RobotoMono',
    textAlign: 'center',
    fontSize: 15,
    padding: 5,
    paddingHorizontal: 10,
    color: '#fff',
  },
  button1: {
    backgroundColor: '#00000000',
    borderColor: '#FF473C',
  },
  button2: {
    backgroundColor: '#000',
    borderColor: '#000',
  },
  button1Text: {
    color: '#FF473C',
  },
  button2Text: {
    color: '#fff',
  },
  p: {
    alignSelf: 'center',
    fontSize: 20,
    fontFamily: 'RobotoMono',
    padding: 10,
    marginBottom: 10,
    color: '#fff',
  },
  input: {
    fontSize: 16,
    textAlign: 'center',
    margin: 5,
    width: windowWidth * 0.7,
    alignSelf: 'center',
    height: 45,
    backgroundColor: '#00000015',
    borderRadius: windowHeight / 20,
  },
  h1: {
    fontFamily: 'RobotoMono',
    fontSize: 24,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
    padding: 5,
    color: '#000',
    width: windowWidth * 0.7,
    marginBottom: 10,
  },
  bottomButtonsContainer: {
    marginVertical: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: windowWidth * 0.7,
    alignSelf: 'center',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingTop: StatusBar.currentHeight,
  },
  scrollView: {
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#ffffff',
    margin: 30,
    padding: 20,
    borderRadius: 10,
    shadowColor: '#d49966',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.2,
    shadowRadius: 29,
    elevation: 5,
  },
  grid: {
    flex: 1,
    flexDirection: 'row',
    marginVertical: 10,
    marginHorizontal: 20,
    padding: 10,
  },
  col: {
    flexGrow: 1,
    fontSize: 18,
    textAlign: 'center',
  },
  legend: {
    fontSize: 16,
    textAlign: 'center',
    paddingBottom: 2,
    marginTop: 5,
    backgroundColor: '#edc0a1',
    borderRadius: 10,
    color: 'white',
    overflow: 'hidden',
  },
  searchInput: {
    margin: 0,
    height: 40,
    width: windowWidth * 0.5,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
})
